### ISSUE TITLE
Japanese translation of installer is garbled.

### ISSUE THREAD

**Issue by chikuzen** [AviSynth/AviSynthPlus#121]
Hi.
A few days ago I tried to install avs+ to my new gear and found that the Japanese translation was garbled like bellow.

![2020-02-09](https://user-images.githubusercontent.com/523171/74101444-2ad7c380-4b7d-11ea-8d49-72a32cbd3375.png)
![2020-02-09 (1)](https://user-images.githubusercontent.com/523171/74101445-2f03e100-4b7d-11ea-8e22-45449d109a73.png)

I don't know anything about innno setup, so if anyone knows more, please fix this.

**Comment by qyot27** [comment]
I think I see what it is.  The translation file ([ja.isl](https://github.com/AviSynth/AviSynthPlus/blob/master/distrib/WinInstaller/Translations/ja.isl)) was converted to UTF-8, but it looks like the Code Page field inside the file still declares itself to be Shift-JIS/932.  Assuming the use of the Unicode version of InnoSetup, I think the only thing needed to fix it should be to [change the code page field to 0](https://www.jrsoftware.org/ishelp/topic_langoptionssection.htm).  It may also need the BOM if it doesn't already, based on [this discussion](https://stackoverflow.com/questions/51066207/utf-8-characters-not-displaying-correctly-in-inno-setup).

The Russian translation almost certainly needs this as well.

**Comment by qyot27** [comment]
Try this installer and see if it's fixed:
http://www.mediafire.com/file/5cf4uyk1ytfwdmz/AviSynthPlus-r2995-linux3-g2865d73d.exe/file

Turns out some of those links were either outdated or something; the BOM makes the installer building process error out, and setting the code page to 0 also does.  My first impulse - setting it to Windows' UTF8 code page 65001 and leaving the files sans BOM - is what actually worked, at least here under Windows-1252.

**Comment by chikuzen** [comment]
I tried your installer and the problem seems to be solved.
Thanks.


2020年2月10日(月) 3:57 qyot27 <notifications@github.com>:
