### ISSUE TITLE
Add ARM support

### ISSUE THREAD

**Issue by SuNNjek** [AviSynth/AviSynthPlus#150]
Since the latest version of AviSynth+ can run on Linux, it would be nice if it also ran on other architectures, such as ARM. I tried compiling on my Raspberry Pi 4 running Raspbian, but it immediately throws an error:
```
[  0%] Built target VersionGen
Scanning dependencies of target AvsCore
[  1%] Building CXX object avs_core/CMakeFiles/AvsCore.dir/convert/convert.cpp.o
c++: error: unrecognized command line option ‘-msse2’
make[2]: *** [avs_core/CMakeFiles/AvsCore.dir/build.make:63: avs_core/CMakeFiles/AvsCore.dir/convert/convert.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:156: avs_core/CMakeFiles/AvsCore.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2
```

**Comment by pinterf** [comment]
Only Intel platform is supported at the moment. The source has to be fully restructured (separate C version from x86 modules) to be able to do that. Definitely a next step but not in the near future. I wouldn't mix this task with other developments now in order to avoid the total chaos :)

**Comment by qyot27** [comment]
It was actually on my short-list of features to work on, and after a couple of weeks of trying to wrangle QEMU into emulating a proper environment and failing (I could get it running headless but that doesn't help too much for a **video** app), I finally got fed up enough and ordered a Raspberry Pi 4B last week; it arrived on Thursday.

And after a day or two getting the right stuff set up on it, I went ahead and hammered the intrinsics, etc. around, and the result:
https://forum.doom9.org/showpost.php?p=1909299&postcount=5534

The rather bleeding-edge patchset is here:
https://github.com/qyot27/AviSynthPlus/commits/arm

Essentially, I found which files have intrinsics in them, created an intel/ subdirectory, and copied the intrinsics-laden sources into the subdir.  I then opened up the ones in the main directory, and removed all (or at least, most) of the intrinsics and CPU detection features from them.  The files where that wasn't possible or ill-advised had those CPU or Intel-specific snippets guarded under an INTEL_INTRINSICS ifdef.

ENABLE_INTEL_SIMD was added as an option to be able to switch it on and off, and when on (the default), Files.cmake uses the files in the intel/ subdirectories and removes the plain-C versions from its file list.  The ones in the intel/ subdirs still have the C versions embedded intact, since this is really just a first step, and the include paths in the sources in intel/ were modified so they could still find the SIMD-enabled versions they would have normally been expecting.

I have not tested it on anything other than Ubuntu 20.04, both x86_64 and on the raspi4.  I'd fully expect there to be things I need to account for on MSVC, for example.  Or for that matter, Windows 10 on ARM.

There's definitely room for some of this to be cleaned up more or have bits implemented so ARM CPUs or plain C compilation is more comfortable.  cpuid will need some help to be able to work with ARM or plain C builds, and anyone wanting to contribute the relevant ARM intrinsics would be open to doing so.

There actually wasn't a whole lot in the neo branch that interfered with this.  I actually did the source splitting and first version against the master branch/3.5.1.  And once I saw that working, I rebased it to sit on top of neo.  For the most part, it was okay.

**Comment by qyot27** [comment]
I force-pushed the arm branch just now, some things needed tweaking when I tried building with MSVC, and other things I was trying with it didn't pan out.  But it does actually build on x86/MSVC, x64/MSVC with and without SIMD enabled, as well as GCC on Ubuntu on x86/x64 and AArch64.

**Comment by qyot27** [comment]
With the release of 3.6.0, ARM compilation is now possible in the master branch.  It also automatically turns the Intel SIMD off if it's not being configured for x86(-64).

Now, it's going to be *slow* on ARM.  There aren't any NEON intrinsics in the code, and the Prefetch code is still segfaulting on the Raspberry Pi 4B running Ubuntu 20.04 aarch64.  But those can be addressed further in post-release bugfixes whenever it can be fixed.

I tried to see if I could get the MSVC ARM64 cross-compiler going with VS2019, but the prompt wouldn't even launch so I could test it (not that I have a Windows 10 on ARM setup to test with, but if Win10 support is fleshed out a bit more for the Pi, it might be do-able once I get an upgraded storage drive).

**Comment by pinterf** [comment]
I have no clue on prefetch code. Theoretically immediate segfault occurs when -pthread is linked properly (std::thread is using that). The "__thread" syntax used in avisynth.cpp for gcc (once we had a segfault problem because of this was missing and used windows msvc convention - thread local variable syntax) should cause no issue.
