### ISSUE TITLE
Prefetch crash

### ISSUE THREAD

**Issue by SudoUser-Sam** [AviSynth/AviSynthPlus#163]
When using Prefetch regardless of how many threads set, it crashes when using LUTComb.

https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/AdvancedDenoising.avsi

Script doesn't matter, just use LUTComb() with any source with prefetch and it will hard lock then crash.

Dependencies : 

https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/LUTDeCrawl.avsi
https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/LUTDeRainbow.avsi
https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/Zs_RF_Shared.avsi

**Comment by pinterf** [comment]
Need Avisynth+ version, 32 or 64 bit, cpu type (but i think it's irrelevant) and the versions of external plugins used by script. Latter can be listed by an avsmeter/avsmeter64 avsinfo output.

**Comment by JySzE** [comment]
AviSynth+ 3.5.1
64bit
Cpu: i9 9900k
Avsinfo output: https://pastebin.com/SjwGgqsj

**Comment by pinterf** [comment]
Thanks, that will be enough. I'm from mobile now till then if you could try my 3.5.2 test build which I linked some weeks ago on doom9 forum. It has many multithreading scriptclip fixes. I wonder if it works for you.

**Comment by JySzE** [comment]
I am unable to locate it.

**Comment by JySzE** [comment]
Ok so it no longer crashes or hard locks but its now giving me this :
![image](https://user-images.githubusercontent.com/25883052/82177006-2feb9380-988d-11ea-869c-6c2857fad5c8.png)

Basic Test Script:
```
MPEG2Source("132.d2v")
LUTCOMB()
prefetch(threads=10)
```
Bare minimum script for easy replication.

**Comment by JySzE** [comment]
this test build fixed this : 

https://forum.doom9.org/showthread.php?p=1906016#post1906016

**Comment by pinterf** [comment]
Yes I wanted to say you try with the April 29th build. https://forum.doom9.org/showthread.php?p=1909682#post1909682

**Comment by pinterf** [comment]
Sorry, could you check that statement again, that the with_arrays version is giving the original error message? For me, they are identical, actual dev version is working as well.

Note1:
I noticed two old CPP 2.5 DLLs in your avsmeter64 avsinfo list. Could you eliminate them for a test? Firstly I do not know why they are kept for, their names indicate that their functionality is covered with RgTools, on the other hand it's always a surprise for me that x64 and Avisynth 2.58-style plugins are able to work together. (Now the case is that plugins with 2.5 interface can cause surprises when using with latest avs versions)

Note 2:
Such scripts with ScriptClip inside are not necessarily multithreading friendly (aside from the technical availability when no syntax or other error is given). They would rely on sequential frame serving and processing, they are using global variables to store actual data which are - in an mt environment - is continously overwritten by different threads. For your specific skeletonized script: I have checked in vdub2 that the output is unacceptable because is non-deterministic, in thread=10 frames are reappearing some frames later, ordr is messed up. I don't know the actual reason of that but the actual script logic may not aware of being run in mt.

**Comment by SudoUser-Sam** [comment]
You were right, i removed the old 2.5 DLLs and retested and it worked fine, I had forgot they were even in there. Thank you!

**Comment by pinterf** [comment]
When you happen to want to use old 2.5 plugins you have to wait for the next (compatibility fix) release.
