### ISSUE TITLE
If pixel_type is set to CS_BGR32 and the width is not multiple of 16, the video will be distorted.

### ISSUE THREAD

**Issue by RHEF19** [AviSynth/AviSynthPlus#185]
If the filter creates and returns a frame whose pixel_type is VideoInfo::CS_BGR32 and width is not a multiple of 16, the output video will be distorted.

DIB has a restriction that it must be a multiple of 4 bytes, but that doesn't matter with RGBA because it is always a multiple of 4.
Also, I confirmed that the image could be passed to GIMP and it would be successfully loaded and displayed as raw RGBA data.
By the way, I haven't tried it with any other pixel_type.

![test](https://user-images.githubusercontent.com/49441484/89215662-062c4800-d604-11ea-981b-833e0af4fbef.png)

**Comment by qyot27** [comment]
Post an example script/workflow that can reproduce this, because
```
BlankClip(width=300,height=240).Subtitle("300x240")
```
doesn't, and neither does (to generate something where any distortion can be seen immediately)
```
Colorbars(width=300,height=240)
```
And both of those default to `pixel_type="RGB32"`.

I tried opening via libavformat and through VDub.  Even had ffmpeg spit out a .bmp and re-open it through `ImageSource`.  Still fine.

**Comment by RHEF19** [comment]
I'm talking about creating a filter plugin with cpp, not avs.
Subtitle has nothing to do with this case.
```
// VideoInfo vi;
vi.width = 300;
vi.pixel_type = VideoInfo::CS_BGR32;
```

Here's a simple example of it.
[ExampleFilter.zip](https://github.com/AviSynth/AviSynthPlus/files/5020076/ExampleFilter.zip)
![example_output](https://user-images.githubusercontent.com/49441484/89253282-26392700-d657-11ea-866c-d6dd9d1b3319.png)

**Comment by qyot27** [comment]
Yes, but with e.g. Colorbars, that filter has to create the video source against the given dimensions, and since it doesn't distort anything, it would have to be compensating¹ for that interaction in width and pixel_type.

¹https://github.com/AviSynth/AviSynthPlus/blob/master/avs_core/filters/source.cpp#L1038

**Comment by RHEF19** [comment]
Ah, the actual number of bytes in width is GetPitch, not GetRowSize.
The Wiki says "frame->GetRowSize(); // in bytes" and I believed it.
Is this perception correct?

**Comment by pinterf** [comment]
Yes, pitch (or stride) is the byte distance between rows. There can be unused bytes at the end of the rows because of alignment reasons. Note that RGB32 is stored upside down.

**Comment by RHEF19** [comment]
Thank you.
