### ISSUE TITLE
3.6.2 test 2 can't use with megui x86

### ISSUE THREAD

**Issue by kedaitinh12** [AviSynth/AviSynthPlus#190]
My error log file:
----[Error] AviSynth Status: inactive - portable AviSynth build cannot be used. The loaded DLL is: 
---[Error] AviSynth: not found

**Comment by pinterf** [comment]
- Why is it an Avisynth problem when Avisynth DLL is not found by megui?
- did you try successfully with earlier avs versions and with which ones?

**Comment by kedaitinh12** [comment]
> * Why is it an Avisynth problem when Avisynth DLL is not found by megui?
> * did you try successfully with earlier avs versions and with which ones?

I see same error with https://forum.doom9.org/showpost.php?p=1922968&postcount=645

**Comment by pinterf** [comment]
Probably its 32bit part accidentally contains debug build of supporting DLLs which would need debug version of Microsoft C++ redistributables. This build was indended to be a quick test for Win10 long filename support, that's why I mentioned it only in the relevant Issue topic, in no way wanted I put it in public.

**Comment by pinterf** [comment]
Nevertheless I prepare you a test3 with no debug builds inside.

**Comment by kedaitinh12** [comment]
> Nevertheless I prepare you a test3 with no debug builds inside.

thanks

**Comment by pinterf** [comment]
I have rebuilt the x64 content as well (though there was no change in source since aug.31. test2, just to match the file dates), and made release builds of the bundled plugins (previous pack contained debug builds of them, which needed the debug VC++ redist package)
Try this one (test2b) and tell me if it works, please:
https://docs.google.com/uc?export=download&id=17ezMUI42I_0vpTlHzd_TzWHXfkUlYXh6

**Comment by kedaitinh12** [comment]
> I have rebuilt the x64 content as well (though there was no change in source since aug.31. test2, just to match the file dates), and made release builds of the bundled plugins (previous pack contained debug builds of them, which needed the debug VC++ redist package)
> Try this one (test2b) and tell me if it works, please:
> https://docs.google.com/uc?export=download&id=17ezMUI42I_0vpTlHzd_TzWHXfkUlYXh6

Thanks, it's work
