### ISSUE TITLE
After using Crop then SeparateFields, Chroma is on the wrong field

### ISSUE THREAD

**Issue by Dwedit** [AviSynth/AviSynthPlus#191]
My script contains this:
```
MPEG2Source("VTS_02_1.D2V")
Crop(4,2,-4,-2)
SeparateFields()
```
When I run it, I see the Chroma get put into the wrong fields, as seen in these screenshots of four consecutive fields:

![field 0](https://i.imgur.com/wfxmL1w.png)
![field 1](https://i.imgur.com/hpmrxI7.png)
![field 2](https://i.imgur.com/yQ8TheX.png)
![field 3](https://i.imgur.com/XXC4gX7.png)

However, if I put the Crop *after* SeparateFields, I get no problem.

**Comment by pinterf** [comment]
Maybe it's not too late, can you provide me the sample? Probably Crop ruins some field-based related clip properties?

**Comment by Dwedit** [comment]
[video-sample.zip](https://github.com/AviSynth/AviSynthPlus/files/6134852/video-sample.zip)

**Comment by pinterf** [comment]
http://avisynth.nl/index.php/Sampling
YV12 format is a subsampled format (both vertically and horizontally, but we have problem because of the vertical subsampling), which means that chroma info is common for each two vertical lines.
When you cropped two lines from the top, you actually cropped  2 luma lines but only a single line from chroma, thus the crop turned the former bottom chroma field into a top chroma field.

Keeping the vertical crop origin as multiple of 4 is O.K. again, the top/bottom for chroma will be properly kept.
```
FFMS2("VTS_02_1.demuxed.m2v")
clip1 = Crop(4,2,-4,-2)
clip1 = clip1.SeparateFields().Info()

clip2 = Crop(4,0,-4,-4)
clip2 = clip2.SeparateFields().Info()

StackVertical(clip1.SubTitle("crop start=2, bad"), clip2.SubTitle("crop start=4, good"))
```

**Comment by pinterf** [comment]
Reason explained, no feedback, closed.
