### ISSUE TITLE
Unknown colorspace error

### ISSUE THREAD

**Issue by infy-infy** [AviSynth/AviSynthPlus#198]
When I'm trying to use AviSynthPlus from ffmpeg, I'm getting an ffmpeg error:
`unknown AviSynth colorspace -1610285048`
I checked ffmpeg sources and it seems they switching on constants that are defined in your header [here](https://github.com/AviSynth/AviSynthPlus/blob/master/avs_core/include/avisynth_c.h) (like AVS_CS_RGBAP12, AVS_CS_YUVA422P16, etc): [ffmpeg source, 449 line](https://git.ffmpeg.org/gitweb/ffmpeg.git/blob_plain/HEAD:/libavformat/avisynth.c)
It seems value -1610285048 doesn't equal to any of these.
ffmpeg file info says it's **yuv420p10le**,PotPlayer says it's **NV12**, and I'm kinda lost.
Can you please tell what is this colorspace, is it supported in AviSynthPlus or it's just ffmpeg developers haven't supported it yet.
Thanks.

**Comment by qyot27** [comment]
Post your script, and versions of FFmpeg and AviSynth+ being used.  A sample might help too, but if it can replicated with just a script, that would be easier.

That said, there are some pixel formats that AviSynth+ does support and FFmpeg does not (yet).  And that is subject to change on FFmpeg's side as they add more, upon which they need to be enabled in the AviSynth demuxer in libavformat (there was [one such update](https://git.videolan.org/?p=ffmpeg.git;a=blobdiff;f=libavformat/avisynth.c;h=2181510c2f36caf03e9ecdb82ed3eb1f02ac80f8;hp=250a489321edc6b150e079d2c960c47be48f6b37;hb=b1681bad33581bc8a018bc9b6ec02761162240e4;hpb=18bbb2dd01f25cf1b36106588a3699c0741bba19) a while back).

From my notes, the list of pixel formats that have yet to be implemented in FFmpeg or at least enabled in the libavformat AviSynth demuxer are:
```
RGBAP14

YUV420PS
YUV422PS
YUV444PS

YUVA420PS
YUVA422PS
YUVA444PS

YUVA420P12
YUVA444P12

YUVA420P14
YUVA422P14
YUVA444P14
```
I think a couple of those might have been added to FFmpeg recently, but I'm not sure.  Generally, it falls into the following categories:

14-bit Planar RGBA
32-bit floating-point YUV and YUVA (float Planar RGB(A) has at least display support, but may still be lacking conversion ops to/from other pixel formats)
12-bit YUVA 4:2:0 and 4:4:4, but **not** 4:2:2, which is supported in FFmpeg
14-bit YUVA

**Comment by infy-infy** [comment]
I use 3.6.1 version of AviSynth+ and n4.3.1-20-g8a2acdc6da of ffmpeg (both are latest, I assume)
Here's script, I changed absolute paths to relative here. Also, I've downloaded latest ffms2.dll as well.
```
try { LoadPlugin("ffms2.dll") } catch (_) { LoadCPlugin("ffms2.dll") }
FFVideoSource("cut.mkv",cachefile="A7-F2-A8-93-B3-4C-27-10-E9-6B-67-3C-B4-00-7A-5A.ffindex",track=0)
Trim(0, 96)
```
Here's the [link for the source](https://mega.nz/file/1F50wCaD#4Mlqpft9SRWSH9YXssR-Y7JFYXeWMV3MwJGjYWDVlQQ) and [index file](https://mega.nz/file/AE4mCKga#mwPCPN9QuflefzZfMrhrPSRhG-2OvQzbHUWbIJNVUjg)
Hope this will help.

**Comment by infy-infy** [comment]
You can reproduce message about unknown colorspace by invoking ffmpeg:
`ffmpeg -f avisynth -i "your\path\to\script\script.txt" -f nut -c copy -v error pipe:1`

**Comment by qyot27** [comment]
I would check to see if there's another copy of AviSynth.dll somewhere in your PATH that ffmpeg may be trying to use instead of 3.6.1.  Namely because that try/catch line would be protecting classic AviSynth from trying to load the FFMS2 C-plugin variant with LoadPlugin, something that doesn't apply to Plus.  And if that C-plugin is new enough, it will try to pass >8bit video straight through without downsampling it.  In versions of Plus after high bit depth was added (in 2016), this will work as expected.  In either classic AviSynth or in pre-HBD versions of Plus, you'd end up hitting that exact `Unknown colorspace` error.

Because I can't reproduce this here, even when I use a relative copy of FFMS2 2.40 and force it to ignore the autoload dirs (where I have the C plugin doing the load work, so I verified that both the C and C++ versions of FFMS2 work on this).

AviSynth+ 3.6.1, FFMS2 2.40, FFmpeg git-fb17ba86a8 (from early June; but there haven't been any updates to the AviSynth demuxer in the time since, so that shouldn't matter).  Even mpv (linked against said FFmpeg) can play it back directly.
```
ClearAutoloadDirs()
try { LoadPlugin("ffms2.dll") } catch (_) { LoadCPlugin("ffms2.dll") }
v1=Version().AddBorders(760,0,760,0,color=$404040).ConvertToYUV420().ConvertBits(10)
v2=FFVideoSource("cut.mkv").Trim(0, 96)
a1=FFAudioSource("cut.mkv")
v3=StackVertical(v1,v2)
AudioDub(v3,a1)
```

Trying with the provided cachefile doesn't help, as it gets overwritten with a refreshed local cachefile tied to my local build(s) of ffms2 and proceeds to still work.  track=0 is basically a no-op if the file only has one video track.

```
E:\Documents>ffmpeg -f avisynth -i test.txt
ffmpeg version r98029+8 master-fb17ba86a8 HEAD-e0cb5ba49a
 contains: avsrgb datetime new_pkgconfig silent_invoke vapoursynth_alt versioninfo
 Copyright (c) 2000-2020 the FFmpeg developers
  built on Jun  2 2020 01:27:59 with gcc 10.1.0 (GCC)
  libavutil      56. 49.100 / 56. 49.100
  libavcodec     58. 90.100 / 58. 90.100
  libavformat    58. 44.100 / 58. 44.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 84.100 /  7. 84.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[avisynth @ 00000242c8fc78c0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, avisynth, from 'test.txt':
  Duration: 00:00:10.08, start: 0.000000, bitrate: 0 kb/s
    Stream #0:0: Video: rawvideo (Y3[11][10] / 0xA0B3359), yuv420p10le, 1920x1184, 24 fps, 24 tbr, 24 tbn, 24 tbc
    Stream #0:1: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
At least one output file must be specified
```

**Comment by infy-infy** [comment]
Now I feel a bit dumb, because I run your script and everything works as expected. I guess `ClearAutoloadDirs()` call helped and now even without it everything works. Indeed, I had 2.6.0 version of Avisynth before, but I uninstalled it and called `Version()` in the script to make sure that 3.6.1 is being loaded.
