### ISSUE TITLE
Array types issue

### ISSUE THREAD

**Issue by TbtBI** [AviSynth/AviSynthPlus#203]
Hi,

Example of the issue: 
```
BlankClip(pixel_type="yv12")
r() #r([1, 2, 3])
function r(clip c, val_array n) #function r(clip c,  array n)/function r(clip c, int_array n)/function r(clip c, val n)
{
return Subtitle(c, String(Defined(n)))
}
```
Above should return error because 'n' is required parameter. The result of 'Defined' is always true. It's the same behavior with types 'array' and 'int_array'. Only when the type is 'val' the behavior is ok.

**Comment by pinterf** [comment]
Probably an array is always defined but in this case it can hold exactly zero elements.
If you familiar to the definition syntax in plugins, the function parameter definition is translated to "[clip]c[n].*"  (* means zero or more elements). 
This was the maximum what I was able to reach with keeping the compatible function definition syntax.
https://github.com/AviSynth/AviSynthPlus/blob/master/avs_core/core/parser/scriptparser.cpp#L168

**Comment by TbtBI** [comment]
> When the function is called, argument values must be supplied (ignoring optional named arguments for the moment – see below).

> Any variable_name which has never been assigned a value is an undefined variable. Undefined variables may be passed to functions, which in turn can determine their status with the Defined function. 

These statements (from http://avisynth.nl/index.php/Grammar#Functions.2C_Filters_and_Arguments ) are broken when type is *_array.

```
BlankClip(pixel_type="yv12")
r()
function r(clip c, val_array "n")
{
return Subtitle(c, String(Defined(n)))
}
```
Above code (1) is returning "true".

```
BlankClip(pixel_type="yv12")
r()
function r(clip c, val "n")
{
return Subtitle(c, String(Defined(n)))
}
```
Above code is returning "false".

```
BlankClip(pixel_type="yv12")
r([1, 2, 3])
function r(clip c, val "n")
{
return Subtitle(c, String(Defined(n)))
}
```
Above code is returning "true".

```
BlankClip(pixel_type="yv12")
r([])
function r(clip c, val "n")
{
return Subtitle(c, String(Defined(n)))
}
```
Above code is returning "true" but explicitly empty array is wrote. It's what *_array types are assuming in code (1)?

```
BlankClip(pixel_type="yv12")
r()
function r(clip c, val_array n)
{
return Subtitle(c, String(Defined(n)))
}
```
Argument "n" must be supplied but there is no error. It's assumed that empty array is given.

```
BlankClip(pixel_type="yv12")
r()
function r(clip c, val n)
{
return Subtitle(c, String(Defined(n)))
}
```
Above code gives error because "n" must be supplied.


 Shouldn't the behavior of *_array types be the same as "val" type?

**Comment by pinterf** [comment]
Yep, not easy.
The caller syntax works exactly the same like the classic Avisynth.

Parameters that are "arrays" in the function definition, can be be given with the usual comma separated way. 

"zero or more of anything" parameters can only occur at the very end or the parameter list because the parameters can begiven in a flattened way (like in classic Avisynth where there had been no [] array syntax). 

Avisynth parser engine is not able to distinguish between not-given or zero-sized arrays parameters. Avisynth was always working with simple 1D arrays which are used for example in Apply, Format, Animate, etc. If the parameters at the given place were not provided, the array size was 0. But the variable was always existing.

Note 1:
int_array and the other fixed-type arrays are type checked. They are only 1D arrays.

Note 2: 
"val_array" (array of anything) type is special. The parser has not even any clue what type of parameters should it expect.
So when you pass a direct array for that (like in the "Dedicated val_array" example) it will take as a distinct value and will put it as a subarray of the given "n" variable. In `r_val(20, "Dedicated val_array", [1,2,3])` n will be an array of size 1, containing the [1,2,3] array in its 0th element

This is because arrays can contain anything, even different type of subarrays or other types in an infinite depth.

```
BlankClip(width=1024,pixel_type="yv12")

r(0, "Dedicated int_array", [1,2,3])
r_val(20, "Dedicated val_array", [1,2,3])
r_val(40, "Dedicated val_array", [1,2,3],["hello","leo",2])
r(60, "Classic int_array", 1,2,3)
r_val(80, "Classic val_array", 1,2,3)
r(100, "Nothing =classic int_array (zero sized)")
r(120, "Nothing =classic val_array (zero sized)")

function r(clip c, int y, string s, int_array "n")
{
  x=0
  if(ArraySize(n) == 3) {
    return Subtitle(c, x=x, y=y, Format("{}: Array length={},[0]={},[1]={},[2]={}",s, ArraySize(n),n[0],n[1],n[2]))
  } else {
    if(ArraySize(n) == 1) {
      return Subtitle(c, x=x, y=y, Format("{}: Array length={}, n[0] length={},[0,0]={},[0,1]={},[0,2]={}", s, ArraySize(n),ArraySize(n[0]),n[0,0],n[0,1],n[0,2]))
    } else if(ArraySize(n) == 2) {
      return Subtitle(c, x=x, y=y, Format("{}: Array length={}, n[0] length={},n[1] length={},[0,0]={},[0,1]={},[0,2]={},[1,0]={},[1,1]={},[1,2]={}", \
       s, ArraySize(n),ArraySize(n[0]),ArraySize(n[1]),n[0,0],n[0,1],n[0,2],n[1,0],n[1,1],n[1,2]))
    } else { 
      return Subtitle(c, x=x, y=y, Format("{}: Array length={}",s, ArraySize(n)))
    }
  }
}

function r_val(clip c, int y, string s, val_array "n")
{
  x=0
  if(ArraySize(n) == 3) {
    return Subtitle(c, x=x, y=y, Format("{}: Array length={},[0]={},[1]={},[2]={}",s, ArraySize(n),n[0],n[1],n[2]))
  } else {
    if(ArraySize(n) == 1) {
      return Subtitle(c, x=x, y=y, Format("{}: Array length={}, n[0] length={},[0,0]={},[0,1]={},[0,2]={}", s, ArraySize(n),ArraySize(n[0]),n[0,0],n[0,1],n[0,2]))
    } else if(ArraySize(n) == 2) {
      return Subtitle(c, x=x, y=y, Format("{}: Array length={}, n[0] length={},n[1] length={},[0,0]={},[0,1]={},[0,2]={},[1,0]={},[1,1]={},[1,2]={}", \
       s, ArraySize(n),ArraySize(n[0]),ArraySize(n[1]),n[0,0],n[0,1],n[0,2],n[1,0],n[1,1],n[1,2]))
    } else { 
      return Subtitle(c, x=x, y=y, Format("{}: Array length={}",s, ArraySize(n)))
    }
  }
}```

**Comment by TbtBI** [comment]
Thanks for the info. It's useful.

Isn't possible to be done an internal check for array size when array type is used in user defined functions so when the same parameter is optional and array size is 0 error to be raised? Also that way Defined() could return false?

**Comment by realfinder** [comment]
now with https://drive.google.com/uc?export=download&id=1f1tfB40Ny0rZcmBApSiulFl6ndfpta4z

```
BlankClip(pixel_type="yv12")
r() #r([1, 2, 3])
function r(clip c, val_array_nz "n") #function r(clip c,  array n)/function r(clip c, int_array n)/function r(clip c, val n)
{
return Subtitle(c, String(Defined(n)))
}
```

it still show "true" I think it should show false, classic Avisynth 2.5 plugins don't have '+' (one or more) array, or there are another issue that make it not possible?

**Comment by realfinder** [comment]
but yes with

```
BlankClip(pixel_type="yv12")
r() #r([1, 2, 3])
function r(clip c, val_array n) #function r(clip c,  array n)/function r(clip c, int_array n)/function r(clip c, val n)
{
return Subtitle(c, String(Defined(n)))
}
```
it's act as it should, the issue now that an array is always defined, maybe Defined function can get new parameter for array like bool "NotZeroArray" and if it true Defined will return false when Array is zero size

**Comment by pinterf** [comment]
I need time, probably many days. It's not easy because of the compatibility workarounds, when comma separated values can also be gathered together to form an array (like in Select final parameters and like in many other plugins) ), they are very hard to understand.

And they should act differently either for named or unnamed function arguments; whether they are passed actually with name or just put there in the parameter list in sequence, without the name when calling the function. And whether they are passed in an old (comma separated) way or passed actually with a [ ] style script array.

**Comment by realfinder** [comment]
yes I aware of that, so I think of 2 solutions, first one and seems more difficult is to allow undefined value in '+' (one or more) array instead of zero size array, and I think maybe this solution need all plugins and functions that use '+' (one or more) to update according to this

second which is easy but not that nice is update Defined() to have new parameter for array case (maybe bool "NotZeroArray" or better name) to return false for zero size, this solution can work for both '+' (one or more) and '*' (zero or more)

**Comment by pinterf** [comment]
Another test, please read considerations in readme.
https://drive.google.com/uc?export=download&id=11Ye6RHYCu99hTZwl2bTyWdvnjObC-K4c

**Comment by realfinder** [comment]
from quick try it seems ok, but in regards to 'Syntax error, "hello" is not an array' I think array parameter should work with non-array value (at least for '+' (one or more)) or it will make things hard for both users and developers, BM3D can working with array and non-array value in same '+' (one or more) parameters but I think it no longer does in this build

**Comment by realfinder** [comment]
yes BM3D_CPU(sigma=0.5) no longer work now, but good to know that BM3D_CPU(sigma=[0.5, 0.0, 0.0]) still work and undefined array update didn't break the plugins (tested both BM3D and vsLGhost)

**Comment by pinterf** [comment]
> 
> 
> from quick try it seems ok, but in regards to 'Syntax error, "hello" is not an array' I think array parameter should work with non-array value (at least for '+' (one or more)) or it will make things hard for both users and developers, BM3D can working with array and non-array value in same '+' (one or more) parameters but I think it no longer does in this build
You get "hello is not an array" error only when you intentionally want to pass it as a _named_ parameter. Which was impossible in the past. When you pass a string or any other simple type in an unnamed list, it will be handled properly and "hello" will appear as an array containing one string element: "hello"

**Comment by realfinder** [comment]
I find another plugin that use array parameter

https://forum.doom9.org/showthread.php?p=1952109#post1952109

MSRCR(sigma=250, lower_thr=0.001, upper_thr=0.001, fulls=true, fulld=true, restore=125.0) no longer work, unless with sigma=[250]

**Comment by pinterf** [comment]
I see that it is passed to a named parameter. The question is that the one who wrote the script really wanted to do this or not? It seems that the array specifier was mistakenly omitted?

**Comment by realfinder** [comment]
don't know, Asd-g didn't mention that non-array can be used https://github.com/Asd-g/AviSynth-Retinex#parameters so you win here :)

but not for BM3D, https://forum.doom9.org/showpost.php?p=1949485&postcount=64 author said that both BM3D_CPU(sigma=0.5) and BM3D_CPU(sigma=[0.5, 0.0, 0.0]) are ok

From my personal opinion, I think array parameter should not refuse non-array value, same as float parameter do with int value

maybe avs+ should convert non-array value that passed to a named parameter to array with one size silently?

**Comment by Asd-g** [comment]
> 
> 
> don't know, Asd-g didn't mention that non-array can be used https://github.com/Asd-g/AviSynth-Retinex#parameters so you win here :)

Retinex, vsLGhost and vmaf (for the array parameters) can accept single value either as array `[x]` or just value `x`. At least for avs+ versions before r3434. I didn't test the latest test builds if the behavior is changed.

**Comment by pinterf** [comment]
This is what I wanted to test whether earlier versions allowed passing a single value as a named parameter foo(arrayparametername=value) - when the parameter itself is a named array. Passing such single parameter in an unnamed way has no problem with this latest version foo(value) will become [value] automatically.

**Comment by realfinder** [comment]
> 
> 
> This is what I wanted to test whether earlier versions allowed passing a single value as a named parameter foo(arrayparametername=value) - when the parameter itself is a named array. Passing such single parameter in an unnamed way has no problem with this latest version foo(value) will become [value] automatically.

"this latest version" upcoming one? I did test with Avisynth_3.7.1_20210917_test15 as I said above but it show error message, with older builds Retinex example above work indeed, same for bm3d, but I think in script cases not always work, at least for this https://github.com/realfinder/UniversalPluginsFolders/blob/master/plugins64%2B/36x/Retinex.avsi wrapper

**Comment by pinterf** [comment]
Indeed, my new error check is invalid which gave _"Script error: the named array argument "sigma" to MSRCP had the wrong type (passed a non-array to an array parameter)"_

Passing single type e.g. "hello" or 0.2 in the place of an array type is valid.
Calling ArraySize() on a single-type AVSValue returns 1.
Indexing a non-array AVSValue with 0 returns the single-typed value itself.

I'm gonna prepare a next build.

**Comment by pinterf** [comment]
Comments, because it did not work

My Script:
```
Global AviSynthPlugins64Dirs = "C:\Projects\Retinex\AviSynth-Retinex-1.0.1\msvc\x64\Debug\"
ColorbarsHD()
MSRCP(sigma=0.5,lower_thr=0.3,upper_thr=0.4)

Function MSRCP(clip clip, float_array "sigma", float "lower_thr", float "upper_thr", bool "fulls", bool "fulld", float "chroma_protect")
{
LoadPlugin(AviSynthPlugins64Dirs + "Retinex.dll")
        MSRCP(clip, sigma, lower_thr, upper_thr, fulls, fulld, chroma_protect)
}

```
A single float "sigma" was passed to the script MSRCP.
Then it calls further to the DLL version of MSRCP.

Let's see how Avisynth is thinking. Since single types are allowed in the place of an array parameter (a single "float" AVSValue is simulated as a 1-element array), the internal MSRCP call is translated as:
`MSRCP(clip, 0.5, 0.3, 0.4, undefined, undefined, undefined)`

Following Avisynth's parser algorithm: when a list of values at the place of parameter "sigma" (type of float array) is found, Avisynth groups the (unnamedly passed) elements together to form a float array. And it founds 0.5, 0.3 and 0.4.

So when the DLL is called it will get a 3-element sigma array and all the other parameters as undefined:
`MSRCP(clip, [0.5, 0.3, 0.4], undefined....)`

Such script array parameters must be passed forward as named parameters or else Avisynth may treat them together with the next, similarly-typed parameter values.

Finally this one worked in my present test build:

```
Function MSRCP(clip clip, float_array "sigma", float "lower_thr", float "upper_thr", bool "fulls", bool "fulld", float "chroma_protect")
{
LoadPlugin(AviSynthPlugins64Dirs + "Retinex.dll")
#        MSRCP(clip, sigma, lower_thr, upper_thr, fulls, fulld, chroma_protect)
# ! named arrays must be passed further as named
        MSRCP(clip, sigma=sigma, lower_thr=lower_thr, upper_thr=upper_thr, fulls=fulls, fulld=fulld, chroma_protect=chroma_protect)
}
```

and it gave similar results for the base call examples
`MSRCP(sigma=0.5,lower_thr=0.3,upper_thr=0.4)`
and
`MSRCP(sigma=[0.5],lower_thr=0.3,upper_thr=0.4)`

**Comment by pinterf** [comment]
test build 16, reenable simple types passed to named array parameters
https://drive.google.com/uc?export=download&id=14b4Zl0HYeRGj2E_0nA0t_IYYWvZuITsP

**Comment by realfinder** [comment]
I got it, thanks, from quick test it seems fine

**Comment by realfinder** [comment]
everything ok but I note that undefined named array act same on both '*' and '+' (both return undefined and false for IsArray())

maybe '*' should always defined as 0 size array whether it named or not, it's not a problem for me now but as a kind of specification/differentiation for future usage

**Comment by pinterf** [comment]
I continued testing and the last build is still not 100%.

Passing a simple float value (as named) to a named array parameter of a script function will keep the parameter type as simple float instead of float array.

As we saw there was no problem when passing this simple float parameter (like "sigma") further to the DLL MSRCP function .
But when you want to access "sigma" as an array _inside the script function_, it will fail with error message.

Fix, cleanup and other tests are in progress.

**Comment by realfinder** [comment]
`But when you want to access "sigma" as an array inside the script function, it will fail with error message.`

I think scripts editors can deal with this case, but yes, it will be more sense if it give array (silent convert simple float to float array)

**Comment by realfinder** [comment]
with test 17

```
BlankClip(pixel_type="yv12")
r()
function r(clip c, val_array "n")
{
return Subtitle(c, String(IsArray(n)) + " " + String(Defined(n)))
}
```

still same as https://github.com/AviSynth/AviSynthPlus/issues/203#issuecomment-922935183

> undefined named array act same on both '*' and '+' (both return false for defined() and IsArray())
> 
> maybe '*' should always defined as 0 size array whether it named or not, it's not a problem for me now but as a kind of specification/differentiation for future usage

**Comment by pinterf** [comment]
So far - not having script array possibility - this rule only was applied for direct plugin API function calls. It is working as expected. Its function signature is "n" so it is named array, but no value is passed for it -> undefined.
The core - even in the past - internally makes difference between a named and unnamed array initialization sequence. So far - not having script array possibility - this rule only was applied for direct plugin API function calls.

But this one (unnamed array parameter): n is defined and n is array and has size of zero. Compatibility again.

```
BlankClip(pixel_type="yv12")
r()
function r(clip c, val_array n)
{
return Subtitle(c, String(IsArray(n)) + " " + String(Defined(n)))
}

```

**Comment by realfinder** [comment]
yes, but the point is to not make 'val_array "n"' same as 'val_array_nz "n"', also kinda of futureproof since maybe scripts editors will need it that way

**Comment by pinterf** [comment]
I suppose it did not found parameter match with the dll "36x/fmtcavs.dll".
What happens when you explicetely call the dll with fmtcavs_fmtc_matrix inside the function?

**Comment by realfinder** [comment]
seems MP_Pipeline no longer work same as https://forum.doom9.org/showthread.php?p=1914443&highlight=MP_Pipeline#post1914443 after named '*' change

**Comment by TbtBI** [comment]
@pinterf,
```
BlankClip(pixel_type="yv12")
r([1, 2, 3])
function r(clip c, val "n")
{
return Subtitle(c, String(Defined(n)))
}
```
Above works.
```
BlankClip(pixel_type="yv12")
r(n=[1, 2, 3])
function r(clip c, val "n")
{
return Subtitle(c, String(Defined(n)))
}
```
Above throws error "passed array to non-array parameter".

**Comment by TbtBI** [comment]
ping @pinterf, just to be sure you didn't overlooked the previous comment.

Shouldn't both codes either work or throw error?

**Comment by pinterf** [comment]
You'll find no straight answer from me in the following lines because I don't know either.

The named version is clear. You cannot do that and the parser warns you. Avisynth explicitely knows that you are intentionally feeding "n" with an array value, which is inhibited probably because of compatibility reasons. (This function signature is a non-matching one, "val" can mean anything except an array. Parser can go on to find a next, better suited function with similar name but with an array-type funcion signature.

But why your first example is working, I don't know. If I remember correctly, such unnamedly passed arrays are "flattened" before trying as if you'd write r(1,2,3).

Do not close this yet, when I have more time then I would return to it. You can ping me, let's say, once per month :)

**Comment by TbtBI** [comment]
Ok, tthanks.

**Comment by pinterf** [comment]
I couldn't let the issue rest in peace :) for months.
First I found the unnamedly passed branch in the code and put there an error message, too (similar to the named version of your example where [1,2,3] was assigned directly to "n").

Then I found that in the place of the "." parameter type ("anything" - that is "val" in script function syntax) it is perfectly fine and secure to pass an explicite array. 

I was trying to ban arrays in place of "." but strangely it turned out that this was the incompatible way. E.g. function IsArray() accepts anything (".") and tells true if it is an array. If I'd not allow "." to accept an array there, it doesn't even reach the function because IsArray would not accept arrays at all and the parser will not recognize the call.

So I think I'm gonna remove the limitation and error messages and "val" (internally ".") will really mean "any type".

**Comment by TbtBI** [comment]
I personally prefer "val" to accept literally any type.

**Comment by pinterf** [comment]
Yes, this is normal. I'm just compiling a new test which will contain this mod as well.

**Comment by Asd-g** [comment]
```
BlankClip(pixel_type="yv12")
Function BalanceBordersaa(clip c, int_array "cTop", int_array "cBottom", int_array "cLeft", int_array "cRight", float_array "thresh", int_array "blur", bool "y", bool "u", bool "v", string "cloc")
{
    Assert(isYUV(c), "BalanceBorders: This is not an YUV/Y clip.")

    y = Default(y, true)
    u = Default(u, true)
    v = Default(v, true)

    ctop_a = Defined(cTop) ?
        \ ArraySize(cTop) == 1 ? [cTop[0], cTop[0], cTop[0]] :
        \ ArraySize(cTop) == 2 ? [cTop[0], cTop[1], cTop[1]] :
        \ ArraySize(cTop) == 3 ? [cTop[0], cTop[1], cTop[2]] :
        \ Assert(ArraySize(cTop) == 3, "BalanceBorders: the cTop values must be no more than three.") :
    \ [0, 0, 0]

    cbottom_a = Defined(cBottom) ?
        \ ArraySize(cBottom) == 1 ? [cBottom[0], cBottom[0], cBottom[0]] :
        \ ArraySize(cBottom) == 2 ? [cBottom[0], cBottom[1], cBottom[1]] :
        \ ArraySize(cBottom) == 3 ? [cBottom[0], cBottom[1], cBottom[2]] :
        \ Assert(ArraySize(cBottom) == 3, "BalanceBorders: the cBottom values must be no more than three.") :
    \ [0, 0, 0]

    cleft_a = Defined(cLeft) ?
        \ ArraySize(cLeft) == 1 ? [cLeft[0], cLeft[0], cLeft[0]] :
        \ ArraySize(cLeft) == 2 ? [cLeft[0], cLeft[1], cLeft[1]] :
        \ ArraySize(cLeft) == 3 ? [cLeft[0], cLeft[1], cLeft[2]] :
        \ Assert(ArraySize(cLeft) == 3, "BalanceBorders: the cLeft values must be no more than three.") :
    \ [0, 0, 0]
}
BalanceBordersaa(101,100,99,200) # error
BalanceBordersaa([101],[100],[99],[200]) # expected behavior
```
I expected that old comma separated way of writing arrays to be not valid for the new *_array type.

**Comment by pinterf** [comment]
I cannot disable it because of compatibility.
With today's (Nov.24) release you can use simple "val" instead of "int_array". In this case you can check if it is a simple type or IsArray and act upon.

**Comment by Asd-g** [comment]
Compatibility for "val", yes.
*_array are new types - I'm not aware of any need of compatibility. Correct me if I'm wrong.

**Comment by pinterf** [comment]
Not the types, that would be easy and clear. But how avisynth parser is working _before_ any function matching procedure.
Many internal functions and plugins accept arrays and these are always fed in a comma delimited way, Avisynth will put them together automatically if the target signature contains array at that position.

**Comment by TbtBI** [comment]
This is odd. I too would expect when using the new array types the old compatibility to be dropped because that compatibility leads to that old workaround array syntax. Now these new types are usable only if one arg is array and it's in the latest position or if more args are array they must be non-mandatory and explicitly used with names when the function is called.

It seems "val" is the only one fully functional type with required some additional checks when array (typical syntax) is wanted.

> With today's (Nov.24) release you can use simple "val" instead of "int_array". In this case you can check if it is a simple type or IsArray and act upon.

Thanks for the update.
