### ISSUE TITLE
Request: RGBAdjust(analyze=true) - support for float input

### ISSUE THREAD

**Issue by TbtBI** [AviSynth/AviSynthPlus#207]
ColorYUV(analyze=true) does support float input but RGBAdjust(analyze=true) doesn't.

**Comment by pinterf** [comment]
http://avisynth.nl/index.php/RGBAdjust
Probably it is unsupported because of 'loose minimum/maximum' which requires setting up a histogram internally.
For a histogram we must choose a 'resolution', for example we have to quantize 32 bit float back to 16 bits in order to achieve histogram functionality with a reasonable speed. Probably I had no time doing this step when I was porting the function to high bit depth. Anyway I'll look at it. If nothing happens in a couple of weeks, I forgot it, please notice me again.

**Comment by TbtBI** [comment]
Ok, thanks.

**Comment by pinterf** [comment]
Ok, its done. The only question: how one would see the data?
I can display it as if it was a 16 bit clip, or turn them back to float, in this case you'll sell 0.001123, 0.991211, ... data.
Please note that this 16-bit fake processing is clipping values between 0..1 even if original float rgb values are out-of-range.

**Comment by TbtBI** [comment]
Thanks.

32-bit RGB
ExtractR/G/B
ColorYUV(analuze=true)

**Comment by TbtBI** [comment]
Probably turn them to float but with some float rounding?
I don't know, do it in a way it will be more accurate.

> Please note that this 16-bit fake processing is clipping values between 0..1 even if original float rgb values are out-of-range.

If I understand correctly RGBAdjust(analyze=true) wouldn't be as accurate as if one looks at the separate channels with ExtractR/G/B.ColorYUV(analyze=true)?

**Comment by pinterf** [comment]
Try this one please
https://drive.google.com/uc?export=download&id=1CpFdkqbNRDwtuHCtWiQ4x49ZCt8W2jkS
min, max, average is exact. Loose min and max is using 16 bit quantization internally.

**Comment by TbtBI** [comment]
Sorry for the late reply.

It's ok.

Thanks.
