### ISSUE TITLE
Progressive clip is considered field-based?

### ISSUE THREAD

**Issue by CrendKing** [AviSynth/AviSynthPlus#225]
VideoInfo has the image_type flag that indicates if a video is field-based or frame-based. And SeparateFields() throws error if a clip is "field-based". Considering the output clip of AVS+'s SeparateFields() sets the field-based flag to true, I'm assuming in AVS+, progressive clip is considered "field-based", and interleaved interlaced clip is considered frame-based?

This is opposite of what VapourSynth behavior: if the [_FieldBased RFP](http://www.vapoursynth.com/doc/apireference.html#reserved-frame-properties) has value 0 (with description "frame based (progressive)"), their SeparateFields() throws error saying "SeparateFields: no field order provided".

I think VapourSynth's behavior makes more sense. It uses one variable to indicate the 3 outstanding cases: progressive, interleaved tff, interleaved bff. Whereas AVS+ uses two boolean variables: VideoInfo::IsFieldBased() and IClip::GetParity(). There are 4 combinations, but for progressive (IsFieldBased() == true), the parity doesn't matter.

Can we
* Reverse the behavior of the field related filters so that progressive is frame-based?
* Redesign the API so that VideoInfo doesn't carry any field related information (same as VapourSynth), and GetParity() returns int?

**Comment by qyot27** [comment]
See my response here, because this topic resulted in a patch to the FFmpeg demuxer that was subject to this confusion, and which I've intended to resolve better, but I haven't had the energy to fiddle with (as I'd prefer to fix this correctly *once* instead of it coming up again months from now because 'oh, there's one more thing'):
http://ffmpeg.org/pipermail/ffmpeg-devel/2021-May/280703.html

Short version: VideoInfo's image_types or the equivalent C interface checks for Field-based video aren't an interlacing check.  All video in AviSynth(+) is Frame-based.  Field-based video is a special mode for filters that have separated the fields into their own half-height frames and need to keep track of them before they get Weaved back together.  The half-height frame is 'progressive' in what is a really loose sense.  Standard Progressive video as well as standard Interlaced video (non-separated or re-Weaved) is Frame-based.

This is an artifact from pre-Plus AviSynth, and as such I strongly doubt anything can or should be done to VideoInfo (pinterf mentioned something similar in the Discussions [topic about the API](https://github.com/AviSynth/AviSynthPlus/discussions/206)), as I can just about guarantee that it would end up breaking plugins.  AviSynth+'s frame properties functionality is what can actually get you the interlaced or progressive status actually intended by this (although I have yet to play with this in doing checks in the libavformat demuxer).

**Comment by CrendKing** [comment]
To summarize what I understand from your comment here:

* The "field-base" related construct are orthogonal to interlacing. A clip being field-based or not is reserved to be used by AVS+ internal (mainly SeparateFields()), and as a source filter, we should always set isFieldBased to false.
* Whether a video is interlaced or not, and if yes what's the dominant field, should be conveyed by the frame property `_FieldBased` just like VapourSynth. And if for [some reason](https://github.com/AviSynth/AviSynthPlus/issues/178) our client can't use AVS+ 3.6+, there is no way to convey the information.

If I misunderstand, please correct me.

Also, even though my upstream is LAV Filters and they provide the dominant field info for their interleaved frames, should I still just always return false for our source clip's GetParity()? Or should I pass through the info from LAV Filters?

**Comment by qyot27** [comment]
That seems more or less correct ([behold the docs entry I had to try and distill it from](http://avisynth.nl/index.php/Interlaced_fieldbased)).  A source filter *could* legitimately use the field-based image_type if said filter has an option to split by field, thus providing half-height frames directly, and the AssumeFieldBased function does exist for users to override things, but generally yes, AFAIK that should be left alone and largely ignored, while the frame property value in 3.6+ gets used to get the actual information.

If LAV Filters supplies the information (I assume you mean from the input video decoder into the source filter, not as LAV Filters opening an AviSynth script), I'd assume that the source filter should copy it into the relevant frame properties and use them.  That is what they were added for.

Some of the internal filters do already use frame properties, or so I thought.  The issue is that source filters need to start setting them (a few of the third-party ones do, upstream FFMS2 notably doesn't, although StvG includes a patch in their builds that does), or else the user has to do it manually first.  Users certainly *could* set them in-script, but I'm not sure how they would do so for low-level stuff like what `_Field` and `_FieldBased` cover.

**Comment by CrendKing** [comment]
Gotcha. I recently added the frame props about fields to VapourSynth, to [my source filter](https://github.com/CrendKing/avisynth_filter/). I was trying to do the same thing with the VideoInfo and GetParity(), only to find confusion. Guess I'll just revert them and switch to do the same frame props changes.
