### ISSUE TITLE
Variable visibility in ScriptClip

### ISSUE THREAD

**Issue by magiblot** [AviSynth/AviSynthPlus#243]
Hi there,

I'm using AVS+ 3.7.0 and I have ran across an unexpected behaviour when referencing variables from `ScriptClip`.

Is it normal that the following does not work...

```sh
function test() {
   S="HELLO"
   BlankClip.ScriptClip("""Subtitle(S)""")
}

test # "I don't know what 'S' means"
```

...even though the following does?

```sh
S="HELLO"
BlankClip.ScriptClip("""Subtitle(S)""")
```

Cheers.

**Comment by pinterf** [comment]
Dunno, probably you have to make it global in order to work from a function

**Comment by magiblot** [comment]
How come I need to make global a local variable that's read-only and whose value is known at script evaluation time?

**Comment by pinterf** [comment]
http://avisynth.nl/index.php/ConditionalFilter
Advanced conditional filtering: part I 
"_Another important issue is that run-time scripts are evaluated in the same context as the main script. Hence only global defined variables in the conditional filter 'environment' can be used inside a function (and vice versa)._"
I can't explain any better. I found it last week and since I never wrote such scripts it took some time to understand the logic.

Part II and III is a must-have reading as well.

**Comment by magiblot** [comment]
Okay. I had skimmed through that page earlier but overlooked that part. Thank you!
