### ISSUE TITLE
Please add the "move" box on Sourceforge to inform

### ISSUE THREAD

**Issue by Neustradamus** [AviSynth/AviSynthPlus#250]
Dear AviSynth team,

Can you add the box on Sourceforge to inform that the project is now on GitHub like other projects?
- https://sourceforge.net/projects/avisynth2/

Thanks in advance.

**Comment by qyot27** [comment]
This is a fork (note the 'Plus'), not the original avisynth2 project.  It didn't move here from there, and co-existed with it for several years.  We have no control over the Sourceforge page.

**Comment by Neustradamus** [comment]
@qyot27: Thanks for your reply, I contact Klaus Post now.

Do you know who manage http://avisynth.nl/ ?

@klauspost: It is possible to add me on the Sourceforge project?
Thanks in advance.

**Comment by klauspost** [comment]
@Neustradamus Sorry. I don't know you, and I don't want to add unknown people to a project with binary releases.

If there is anything specific I can do, let me know, and I will see if I can help.

**Comment by Neustradamus** [comment]
@klauspost: Thanks for your reply!

If not me, it is possible to add the current team?

It is possible to add the "move" box like handbrake for example?
- https://sourceforge.net/projects/handbrake/

Time to import old tickets on GitHub and remove it from Sourceforge.
- https://sourceforge.net/p/avisynth2/_list/tickets

Who manage http://www.avisynth.nl/ + http://www.avisynth.org/?
Time to add the certificate and to have one website...

Note sure that it is good to have:
- https://sourceforge.net/p/avisynth2/svn/
- https://sourceforge.net/p/avisynth2/svn/HEAD/tree/

Thanks in advance.

**Comment by klauspost** [comment]
@Neustradamus 

> It is possible to add the "move" box like handbrake for example?

Should it point to this project? I am not against it, but I honestly haven't followed development for many years, so I don't know if that is an appropriate thing to do.

> Time to import old tickets on GitHub and remove it from Sourceforge.

I don't really see any point. Issues are extremely old and most are probably irrelevant.

> Who manage http://www.avisynth.nl/ + http://www.avisynth.org/?

No idea.

**Comment by Neustradamus** [comment]
> @Neustradamus
> 
@klauspost
> > It is possible to add the "move" box like handbrake for example?
> 
> Should it point to this project? I am not against it, but I honestly haven't followed development for many years, so I don't know if that is an appropriate thing to do.
> 
A lot of commits there are...
Yes to https://github.com/AviSynth, it is the best solution, I think.
> > Time to import old tickets on GitHub and remove it from Sourceforge.
> 
> I don't really see any point. Issues are extremely old and most are probably irrelevant.
> 
Ok please disable it in the admin project ^^
> > Who manage http://www.avisynth.nl/ + http://www.avisynth.org/?
> 
> No idea.
Badly...

You can disable too:
- https://sourceforge.net/p/avisynth2/svn/
- https://sourceforge.net/p/avisynth2/svn/HEAD/tree/

This page can be disabled too or edited:
- https://sourceforge.net/projects/avisynth2/support

You can add in more the "move" box, the link in tabs to https://github.com/AviSynth.

**Comment by klauspost** [comment]
@Neustradamus I marked it as "Abandoned" and added links.  Tried disabling Bugs/Features, but couldn't find any setting beyond "DELETE EVERYTHING".

**Comment by qyot27** [comment]
avisynth.nl is the current Wiki location, and is much more expansive in content (all the AviSynth+-related pages/additions on the Wiki are on .nl, and the info on the Wiki's main page links to the landing page at https://avs-plus.net and to the Github repo here). I can't remember what Wilbert had said about the status of the .org site, but considering the page history and talk pages result in 404s...

As far as the tickets on Sourceforge go, I don't think there's any reason to import them here.  Most of them probably no longer affect Plus, if they ever did*.  After the fork, we did merge in changes that happened in 2.6, but by the time the original project went dark, there weren't many changes that hadn't already been fixed in Plus or had been refactored away in an entirely different manner.  It doesn't mean that there might not be things that still affect Plus that also affected 2.6, but at this point I think if we want to identify those, just open new issues for them if you see that it affects both 2.6 and Plus.

*and some of the Feature Requests were added to Plus years ago, like multithreading and high bit depth.  And the [bug report about Unicode](https://sourceforge.net/p/avisynth2/bugs/169/) ended up being made irrelevant by both A) most people moving away from using DirectShowSource as a source filter and B) OSes using UTF-8 as the native encoding; Linux, macOS, the BSDs, and Haiku have all used UTF-8 nearly forever, so this was never an issue for AviSynth+ on those platforms, and Windows 10 finally allows users to set UTF-8 as their native codepage instead of the oddball way `chcp 65001` worked in the Command Prompt (and which didn't fix that problem anyway, IIRC).  That actually means [that even 2.6 is completely happy with international characters so long as Windows was set properly](https://forum.doom9.org/showpost.php?p=1909790&postcount=9), without needing any special handling.

**Comment by Neustradamus** [comment]
@klauspost: Thanks for your changes.

There are options to export in admin.

Attention, we do not know who manage the domain .org (created in 2020) but it is hosted by SF I think, you can see in admin.

Like you are admin in SF:
1/ You have a lock at the end of the menu to manage, after you will have a gear on several tabs.
2/ https://sourceforge.net/p/avisynth2/admin/

Screenshots:
- https://i.ibb.co/80jWpDc/sourceforge-gear-files.png
- https://i.ibb.co/3r05P3H/sourceforge-gear-tickets.png
- https://i.ibb.co/zJKpGmL/sourceforge-gear-help.png
- https://i.ibb.co/L0zdgjH/sourceforge-gear-code.png
- https://i.ibb.co/cgJjF3Z/sourceforge-add-new-tab.png
- https://i.ibb.co/L6zMHVr/sourceforge-admin-welcome.png
- https://i.ibb.co/Rzj95xt/sourceforge-admin-metadata.png

I think that new devs can be added in the SF project.

**Comment by qyot27** [comment]
Honestly, what harm is there in just leaving the Sourceforge page alone?  It's literally not been an issue for four or more years.  I mean, SF removed CVS access in 2017, by which point I think most everyone keeping track of any code development there got the hint, because there's only one or two tickets that were opened after that, and that was still three or four years ago.

It just seems odd for this to suddenly be brought up as a concern, apart from some specific sentiment beyond 'everything needs to move away from Sourceforge' (given the similar issues that got opened on the Github repos for mpc-hc, mplayer, etc.).

**Comment by klauspost** [comment]
@Neustradamus I have made the changes I feel comfortable with.

**Comment by Neustradamus** [comment]
@klauspost: The box has not been added...
No tab link in the menu...
Can you change the homepage too?

Please do an export https://sourceforge.net/p/avisynth/admin/export.

It has not hosted on SF, only the homepage work, it has been copied: http://www.avisynth.org/mediawiki/
Really not good!

The goal, I think that you understand, it is the continuity by a good dev team.

Thanks in advance.

**Comment by qyot27** [comment]
I've been polite up to now, but if the badgering continues, I will put on my mod hat.  As it stands, this isn't really relevant to our issue tracker anymore, either, so I'm closing this.

**Comment by Neustradamus** [comment]
@qyot27: I help the project here, no?
The continuity is important.

There is since 2020, a fake avisynth.org.

And @klauspost has done some changes to inform that the project is now here, not complete for now, it is in progress.

@klauspost: If export is "not possible", there is a "Delete Everything" for Tickets section.

And here: https://sourceforge.net/p/avisynth2/admin/, please change:
- https://i.ibb.co/H4s28HT/sourceforge-admin-metadata-for-avisynth2-project.png

```
Homepage: https://github.com/AviSynth
Move to: https://github.com/AviSynth
Short description: "Visit https://github.com/AviSynth"
Fill description: "Legacy repository for Avisynth. Visit https://github.com/AviSynth for updated informations."
Prefered support page: None

```

We are in 2022, the future is here ;)

Thanks in advance.

**Comment by qyot27** [comment]
And how was there a problem with continuity?  The projects co-existed for three years, it was generally clear that classic AviSynth and AviSynth+ were separate.  We didn't 'take over' the development of the classic project, we simply stayed in active development, and even if now we would be considered the main project by virtue of development activity and commit volume, the history of both the fork and AviSynth history generally means that the differentiation between the classic project's hosting and ours is not really an issue.  I certainly never considered it a problem.  My point is, if there ever was a torch to pass from classic to Plus, it got passed years ago in a *de facto* capacity without any need for Plus to be specifically acknowledged for it.

The only thing I do tend to see are people making the mistake of saying 'Windows-only' as a blanket statement, because they aren't aware that we also support other OSes and CPU arches now.  But that's a recent enough change (March 2020) to be understandable; not everyone is acutely aware of happenings on the Doom9 forums where most of the development and community discussion still happens.  After 20 years of various notable incarnations of AviSynth being Windows-only, thinking that it is still is isn't great, but again, not everyone pays close attention to announcements (and trying to get the classic project to change a bunch of things on a completely different hosting service to point at the fork likely won't solve that problem, either, in addition to continuing insistence to do so coming across in very poor taste, hence the warning in my last post).

**Comment by Neustradamus** [comment]
@qyot27: It is important to have a good communication, it is important to inform people by all possibilities where is the new place.

With this, more users, more developers, more contributions, etc.

**Comment by Purfview** [comment]
@Neustradamus 
@klauspost

Only avisynth.nl now is used as wiki https://forum.doom9.org/showthread.php?p=1952228

**Comment by Neustradamus** [comment]
@Purfview: Thanks for your comment!

There was a problem of communication in team... Wilbert has not spoken with other and another member has not taken the domain name, the .ORG was better than .NL.
```
Yes i know. I'm not the owner anymore. I didn't prolonge the registration of avisynth.org, since it costs money and i think it's of no use anymore.
I don't understand why you see some old contents of our wiki (clicking on most links give you a 404 though).
```
- https://forum.doom9.org/showthread.php?p=1951636#post1951636

--------------------

@klauspost: First request: Like I have already requested before: time to remove the .ORG and replace by https://github.com/AviSynth -> Directly in admin page: https://sourceforge.net/p/avisynth2/admin/overview to change:
- "Homepage"
- "Full Description"
- "Moved Project to"
- "Preferred Support Page (for users of your project)"

In this page, you can add to in "Short Summary" too.

On https://sourceforge.net/projects/avisynth2, you have a lock at the end of the menu to manage, after you will have a tabs "Add New" -> "External Link", you can add a new tab "GitHub" with a link to: https://github.com/AviSynth.

Second request: About tickets, it is not good to see "Sorry Anonymous submission's are no longer permitted due to some dick head filling the tracker with spam.",  On tab (lock -> gear -> ...)
"Project Trackers" part will be automatically here too: https://sourceforge.net/projects/avisynth2/support.

Thanks in advance!

-------------------

@Purfview: It is not possible to move the Wiki into this GitHub which is not enable?
- https://github.com/AviSynth/AviSynthPlus/wiki
