### ISSUE TITLE
AvisynthCUDAFilters

### ISSUE THREAD

**Issue by Reel-Deal** [AviSynth/AviSynthPlus#296]
Hi there pinterf, hope everything is going well :)

Sorry about posting here but there is no issues section on the AvisynthCUDAFilters repo. I was wondering if you ever provided compiled versions of these filters? I know nekopanda did but if I understand correctly they are not compatible with AVS+ 3.7.2. @videoh has a few questions on how the CUDA specific filters work: https://www.rationalqm.us/board/viewtopic.php?f=14&t=1180&p=16314#p16314

I wanted to give it a try but I could not find already compiled CUDA filters.

**Comment by videoh** [comment]
I compiled the neko sample invertneg(). As I describe in the thread at DG forum, it fails with AVS+ 3.7.2. So any help you could give us would be greatly appreciated. And an answer to this question: Does the AVS+ CUDA framework allow for a pipeline of filters running on the GPU transferring data back to the host only after the last filter? If so, how would that be done?

Thank you.

**Comment by qyot27** [comment]
The release builds don't have the CUDA support enabled, because I don't have the hardware to test it.  Both of the Nvidia cards I have pre-date CUDA's existence: a GeForce 6200 PCI, and a Quadro FX 4500 PCIe 1.0.

[The more recent dev test builds @pinterf provided have it enabled, I think:](https://forum.doom9.org/showthread.php?p=1964833#post1964833)
> I stopped including "CUDA" in the name, it's basically a non-XP 64 bit version of Avisynth+ which _can_ accept specially written CUDA Avisynth plugins. Knowing the fact that almost no one is using these Avisynth-Neo CUDA-aware interface I removed it from the name. Such an Avisynth+ build does not use CUDA at all, it is just able to host such filters; the only known plugin set which is compatible with this interface is https://github.com/pinterf/AviSynthCUDAFilters which is there for people/developers who'd like to play with this interface.

What I can remember of how this went is that AviSynth-Neo gained the reputation as the 'CUDA' fork (in reality, it changed more than that, like adding frame properties and caching/prefetching fixes and other assorted things) during the period in 2016-2019 that pinterf's repo was the *de facto* Plus HEAD.  But it wasn't all that well documented in English (I have no idea if it was any better documented in Japanese).  I want to say commits to the Neo repo stopped in 2018, but many of the other changes there were desirable for inclusion back upstream in Plus, and were merged in Spring 2020 with 3.6.0.

My recollection was that, at that time, the CUDA-related changes in Neo weren't merged back, because it was too different to re-integrate easily; but over time, some of the changes have filtered their way upstream as it became possible to do so (although I may be wrong here; maybe all of it was merged back, with changes to make it function with the post-3.4 upstream versions of Plus, but not enabled all at once).  I still don't know if it's at 1:1 parity with what Neo had, and if not, I don't know if Neo was able to pipeline everything on the GPU or not.

I tried my hand at getting both the CUDA option in the core and AviSynthCUDAFilters to build, result here:
https://www.mediafire.com/file/zo2fui1qk7b5tex/AviSynth%252B_r3686_CUDA.7z/file

I have no idea if it was built correctly, because like I said before, I have no way to test it.  One thing to note are that the Masktools and NNEDI subprojects did not build, and from skimming through the build notes, that looks more complicated and I'd have to really try to tease that out at a later time.

**Comment by Reel-Deal** [comment]
> The release builds don't have the CUDA support enabled, because I don't have the hardware to test it. Both of the Nvidia cards I have pre-date CUDA's existence: a GeForce 6200 PCI, and a Quadro FX 4500 PCIe 1.0.

I remember seeing [a post from you](https://forum.doom9.org/showthread.php?p=1960313#post1960313) saying you don't enable CUDA but I totally forgot that you released the last stable version of AviSynth+. 

> I tried my hand at getting both the CUDA option in the core and AviSynthCUDAFilters to build, result here:

Thanks, I will test it out and get back to you if I encounter any problems.

**Comment by videoh** [comment]
There's no documentation so it doesn't exist. The code was abandoned 4 years ago. There is no support. No links for working binaries. On and on. It was all just a dream.

**Comment by Reel-Deal** [comment]
> I have no idea if it was built correctly, because like I said before, I have no way to test it. 

I can't get it to work, I get the following error: Avisynth read error: CAVIStreamSynth: System exception - Access Violation at 0x0000000022267810

Script
```
ColorBarsHD().ConvertToYV12()
OnCPU(2)
AvsCUDA_Spline64Resize(640,360) 
OnCUDA(2)
```
If I comment out the last 2 lines it works.

**Comment by videoh** [comment]
I suggest don't waste your time. There is nobody willing and able to give supported. It is DEAD DEAD DEAD.

**Comment by pinterf** [comment]
Thanks for noticing it, https://github.com/pinterf/AviSynthCUDAFilters now has _Issues_ and _Discussions_ section

**Comment by Reel-Deal** [comment]
> Thanks for noticing it, https://github.com/pinterf/AviSynthCUDAFilters now has _Issues_ and _Discussions_ section

Thanks pinterf.

**Comment by pinterf** [comment]
Yep, unfortunately there is no support for it. Though I was able to run those filters on my machine, successfully run KTGMC instead of QTGMC on my machine (onCUDA/onCPU at the start and in the end), and even bought the cheapest CUDA aware video card in case of I had time for it. Yes, it was jut a dream. 

I put my translations and build experiences here:
https://github.com/pinterf/AviSynthCUDAFilters/tree/master/documentation

Nekopanda has transformed almost all frequently used filters (though with limited features and parameter settings) which was used by his KTGMC pipeline. That meant that there was no memory transfer needed during the whole filter chain. (resize, masktools lut, nnedi3, etc...); after source filter the whole filtering process was done on the GPU and only once, at the very end was the frame transferred back to CPU memory.

Nekopanda's avs+ fork interface is not compatible with present Avisynth+ interface. Nekopanda's DLL would crash for this very reason. It has its own frame property support, while I pulled over a different frame property concept from Vapoursynth. Concept of script arrays was killed in that fork as well.

Official Avisynth+ releases are w/o CUDA option enabled. In order to start the experimenting, CUDA must be enabled in Avisynth+'s build options. It does not mean that such an Avisynth+ will require CUDA card, it simply makes possible to load such CUDA plugins.
