### ISSUE TITLE
There is no function named 'AviSource'

### ISSUE THREAD

**Issue by jonechkon** [AviSynth/AviSynthPlus#303]
Hello,
I'm trying to use avisynthplus on Arch linux.
Have tried installing it from official repositories and AUR (3.7.2).
Showing the version in VLC player works, but when I try to open an .avi with

> AviSource("file.avi")

i only get 

> [avisynth @ 0x561f9cdde540] Script error: There is no function named 'AviSource'.

Same for WavSource and FmpegSource2.

Any suggestions would be much appreciated.

Thanks and greetings

**Comment by qyot27** [comment]
FFmpegSource2 requires the ffms2 package, although per issue #194, it's probably a better idea to have a minimal (read: muxers/encoders disabled) static version of FFmpeg installed somewhere in a custom prefix to build FFMS2 against because of shared builds of FFmpeg conflicting with themselves.  Or just use [avs2yuv](https://github.com/DJATOM/avs2yuv) to pipe into whatever program you want to use.

The same thing also applies to the filters in LSMASHSource - minimal static FFmpeg is recommended to avoid linking conflicts.

AVISource/WAVSource is exclusive to Windows, as it uses Video for Windows to open the files.

**Comment by ctrlcctrlv** [comment]
Note: If you will attempt to take @qyot27's advice you must compile lsmash as:

```diff
diff --git a/configure b/configure
index de5faed..0a963c1 100755
--- a/configure
+++ b/configure
@@ -113,7 +113,7 @@ IMPLIB=""
 
 TOOLS=""
 
-CFLAGS="-Wshadow -Wall -std=c99 -pedantic -I. -I$SRCDIR"
+CFLAGS="-Wshadow -Wall -std=c99 -fPIC -pedantic -I. -I$SRCDIR"
 LDFLAGS="-L."
 SO_LDFLAGS='-shared -Wl,-soname,$@ -Wl,--version-script,liblsmash.ver'
 LIBS="-lm"
```

```bash
./configure # --prefix=/opt
make -j $(nproc) install install-lib
```

You can then compile LSMASHSource with:

```bash
# PKG_CONFIG_PATH=/opt/lib/pkgconfig
meson setup build # -Dprefix=/opt
(cd build; ninja install)
```

You can then _finally_ use AviSynth+. I don't think the lack of AviSource on GNU/Linux is particularly well documented.
