### ISSUE TITLE
`ConvertToRGB()` misbehaving with `ConvertBits()`

### ISSUE THREAD

**Issue by Enyium** [AviSynth/AviSynthPlus#323]
```
FFVideoSource("C:\path\to\file.mp4")

#ConvertToY()
#ConvertToYUV444()
#ConvertToPlanarRGB()
#ConvertToPlanarRGBA()

ConvertBits(32)

ConvertToRGB() # RGBA
ConvertBits(8)

# Sometimes there's the error message "ConvertToRGB: conversion is allowed only
# from 8 or 16 bit colorspaces", and sometimes the output is corrupted (green-tinted/
# very dark/striped lengthwise with psychedelic colors and zoomed in). Is there a
# check missing? (When saying "convert functions", I'm not referring to
# `ConvertToRGB()`, and only to the four above.)
#
# - Error: Every convert function containing `Y` plus `ConvertBits(32)`
# - Corruption: Every convert function containing `PlanarRGB` plus `ConvertBits(32)`
# - Corruption: Every convert function plus `ConvertBits(12)` (similar for 10 and 14 bits)
```

**Comment by Enyium** [comment]
Related to #282?

**Comment by qyot27** [comment]
`ConvertBits(32)` converts the video to 32-bit single-precision float per plane.  We only support Packed RGB in 8-bit integer per channel (RGB24/RGBA32) and 16-bit integer per channel (RGB48/RGBA64).  So any attempt to go from one of the packed RGB formats to float should spit back an error¹, and any attempt to go from one of the float formats to packed RGB should result in an error².

in FFmpeg (or by extension, mpv), since it's easy to just copy-paste:
¹[ffmpeg/demuxer] avisynth: ConvertBits: invalid bit-depth for packed RGB formats, only 8 or 16 possible
²[ffmpeg/demuxer] avisynth: ConvertToRGB: conversion is allowed only from 8 or 16 bit colorspaces

The 'corruption' (and an error occurring for converting YUV formats to float) as described sounds more like an issue with the display.  What client program are you using to check this?  Even FFmpeg doesn't support all of the pixel formats AviSynth+ does ([WIP branches notwithstanding](https://github.com/qyot27/FFmpeg/commits/avs_pixfmts)), but the description sounds quite a lot like what happens when a format is force-enabled when the display program doesn't have any proper scaling functionality for that case.

**Comment by Enyium** [comment]
> The 'corruption'... as described sounds more like an issue with the display. What client program are you using to check this?

The last two commands are responsible to ensure an output format that all players understand (packed RGBA, 8 bits per component). That all players understand it is confirmed by other filter chains that still end with these two commands where there are no problems.

It's the same effect in MPC-HC and PotPlayer on Windows (`ConvertToPlanarRGB()` with `ConvertBits(32)`):

![potplayer](https://user-images.githubusercontent.com/123484196/216160473-4c5571c1-3b9a-48c2-a68d-d6d39645f3eb.png)

**Comment by Reel-Deal** [comment]
That might be a limitation of the client program as qyot27 said. A script with just ``Version(pixel_type="RGBPS")`` works for me in AvsPmod and MPC-HC but not VirtualDub2.

> Couldn't locate decompressor for format '[0][0][0][0]' (unknown)
VirtualDub requires a Video for Windows (VFW) compatible codec to decompress video. DirectShow codecs, such as those used by Windows Media Player, are not suitable.

What AviSynth+ are you using?

**Comment by qyot27** [comment]
Chances are the issues are stemming from outdated player software that are still on a version of LAV Filters from before one of the two commits adding high bit depth in the AviSynth demuxer (one from 2016, prior to the end of the original mpc-hc github repository, and one from 2019 that enabled the two Planar RGB float formats and YF32).

The [currently maintained version of mpc-hc](github.com/clsid2/mpc-hc) does have a new enough version of LAV Filters to handle what the upstream AviSynth demuxer is currently capable of, though.

![screen](https://user-images.githubusercontent.com/1296881/216192254-1683aace-f615-4227-9902-07f390ae4456.png)

**Comment by Enyium** [comment]
I have the exact same version of MPC-HC as you, @qyot27. And PotPlayer should have a different engine, still it has the same problem. PotPlayer says: "You are using the latest version of PotPlayer."

```
Version(pixel_type="RGBPS")
```

In MPC-HC:

![mpc-hc-1](https://user-images.githubusercontent.com/123484196/216242465-9ae82bd2-0b49-43f4-9bc0-552839bd8bd1.png)

In PotPlayer:

![potplayer-1](https://user-images.githubusercontent.com/123484196/216242502-9ac1e426-82ea-4156-a276-96080f256bb5.png)

---

```
Version(pixel_type="RGBPS")

ConvertToRGB() # RGBA
ConvertBits(8)
```

In MPC-HC:

![mpc-hc-2](https://user-images.githubusercontent.com/123484196/216242642-1304396b-1cea-44a8-b54d-7cdd9cd3ccde.png)

In PotPlayer:

![potplayer-2](https://user-images.githubusercontent.com/123484196/216242671-392ea2aa-1e62-44cc-9468-2eef3befdfe4.png)

---

How could AviSynth not be involved?! Does any of the script functions above call into LAV filters or whatever?

**Comment by Reel-Deal** [comment]
```
Version(pixel_type="RGBPS")
ConvertToRGB() # RGBA
ConvertBits(8)
```

You must be using AviSynth 3.7.2 (or older?). This has been fixed in git. Using a [test version](https://forum.doom9.org/showthread.php?p=1981396#post1981396), you would get this error message: "Avisynth open failure: ConvertToRGB: conversion is allowed only from 8 or 16 bit colorspaces"

**Comment by Enyium** [comment]
Yes, I have v3.7.2 installed. I can confirm that, with my own fresh build, I don't get corruption anymore, but an error message.
