### ISSUE TITLE
Installing 3.7.3 on Linux

### ISSUE THREAD

**Issue by dmsm** [AviSynth/AviSynthPlus#341]
I'm wondering how I can install version 3.7.3 on a Linux environment. I am able to build from the source in this repo, but this appears to be 3.7.2, and it looks like the builds at https://gitlab.com/uvz/AviSynthPlus-Builds are not for Unix systems.

**Comment by qyot27** [comment]
3.7.3 doesn't actually exist yet.  So you can't, but in fact you probably already are.

The Windows builds that show that version number are just regular git builds (or perhaps testing builds slightly before a feature landed in git) with the version number modified.  The real version bump typically occurs right before the release actually happens.  How we facilitate git builds may change in the future to try and clarify this situation, especially since release pacing has slowed down, which stands to make it confusing that there are builds with the next release number floating around when it hasn't been tagged or released yet.

The clue towards this is to look at the revision number in the output of Version(), which lists the revision number, originating branch, and CPU architecture in parentheses after the release number.  The actual 3.7.2 release is r3661, while the master branch is r3944 (which most of the '3.7.3' builds should be closer to).

Now, if you'd actually built from the '3.7' branch, then yeah, you're really running 3.7.2 r3661.
