### ISSUE TITLE
[Feature request] Text alignment

### ISSUE THREAD

**Issue by qyot27** [AviSynth/AviSynthPlus#366]
Primarily for Info() and propShow(), but really any of the text functions should have the ability to change the alignment of the text in orientation to the screen.  Subtitle has this, but for diagnostic filters this could be more immediately necessary just to aid legibility (another option to optionally create a solid color canvas overlay behind the text might also be welcome for diagnostic filters).

As it stands, if you call both Info() and propShow() on the same clip, it just spits out a garbled mess of text overlaid over other text.  At the very least, being able to do Info(align=9) or vice-versa for propShow() would be able to keep the outputs separate from each other.

**Comment by pinterf** [comment]
My only consern about the right alignment is that the individual lines are of variable length, so depending on the actual (multiline) text to display it may start at different x positions, since alignment takes into account the text length. But yes, I see why it is needed.
As for solid canvas overlay: afaik Text already supports a semitransparent background through FF and FE of msb halo bytes.

**Comment by pinterf** [comment]
Preliminary: after fixing #368, this feature will be easier to implement.

**Comment by pinterf** [comment]
I'm closing this as feature is implemented for relevant filters: Info and propShow
