### ISSUE TITLE
SkewRows() is useless in it's current implementation - too coarse/imprecise (or it's just a bug?)

### ISSUE THREAD

**Issue by vasyl-zabolotniy** [AviSynth/AviSynthPlus#396]
From documentation:
> The width and height of the output clip are therefore altered **slightly**, as follows:
> OutWidth = InWidth + skew   (signed skew values acceptable)

....
The output does not look like that at all - smallest possible SkewRows(1) acts more like OutWidth = InWidth * (1+0.75)
Which is far from *slightly*. Please consider fixing it.

**Comment by qyot27** [comment]
The 'slightly' comment has nothing to do with what it *looks* like, but with the dimensions of the output image.

    Version() = 513x154
    Version().SkewRows(1) = 512x155

    Version(width=7680,height=4320) = 7680x4320
    Version(width=7680,height=4320).SkewRows(1) = 7681x4320


The description of what the filter actually does is shown in the example images ([the actual code implementation is here](https://github.com/AviSynth/AviSynthPlus/blob/2b55ba40ec22652d72121fcef56b46da1fc2e427/avs_core/filters/misc.cpp#L196)).  It was intended to fix a very specific problem that I honestly haven't seen happen in a long time, but was more common when people still relied on AVISource and DirectShowSource with some random VfW or DirectShow codec instead of better source filters.

https://forum.doom9.org/showthread.php?p=1532868#post1532868

> That is a classic example of row skewing. The right and left sides of the image being stitched 1 pixel further across as you scan from bottom to top is the key hint. SkewRows(1) is designed to fix exactly this. The true width should have been 1367 not 1366. Unfortunately the last 768 pixels from the end of the top row will be missing.

**Comment by vasyl-zabolotniy** [comment]
I got it, thanks for clarification! 
I think I just found perfect alternative for what I need - HShear() function from [(AviSynth Rotate plugin](http://avisynth.nl/index.php/Rotate))
