### ISSUE TITLE
user_avs_plugindir_configurable and system_avs_plugindir paths are absolute paths set at compile time - not good.

### ISSUE THREAD

**Issue by phoyd** [AviSynth/AviSynthPlus#412]
I tried the vcpkg port for avisynthplus today and found that plugins are not auto loaded. Upon inspection I found that the values for the default plugin directories are determined at compile time in way that makes it impossible to move or package the build. Since vcpkg moves the packages after installation, this breaks module loading.

This is what I get in `avisynth_conf.h` in my build: 
```
#define user_avs_plugindir_configurable "/home/phoyd/.local/lib/avisynth"
#define system_avs_plugindir "/home/phoyd/Projects/github/phoyd/scanner_cleanup/scripts/vcpkg/packages/avisynthplus_x64-linux-dynamic-release/lib/avisynth"
```
because `avs_core/avisynth_conf.h` in the sources contains this: 
```
#define user_avs_plugindir_configurable "@USER_AVS_PLUGINDIR_LOCATION@"
#define system_avs_plugindir "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@/avisynth"
```

### Problem 

* when packaging the name of the building user is burned into `user_avs_plugindir_configurable` and plugins are not loaded from `$HOME/.local/lib/avisynth` for anyone else.
* avisynthplus can not be used in an appimage or flatpak, because the location of the system plugin directory is under a runtime location now.

### Suggestion

* set `user_avs_plugindir_configurable` at runtime by querying the current user.
* set `system_avs_plugindir` to the avisynth/ directory that exists in the same directory as `libavisynth.so` or avisynth.dll using `dladdr` in POSIX and `GetModuleHandleEx`, `GetModuleFileName` in Windows.

This would yield to the behaviour that https://avisynthplus.readthedocs.io/en/latest/avisynthdoc/contributing/posix.html#plugin-autoloading describes.

**Comment by qyot27** [comment]
Fixed in https://github.com/AviSynth/AviSynthPlus/commit/4c275c23c7a9799773de30257952fd81140f1059, https://github.com/AviSynth/AviSynthPlus/commit/9437d46bfd65c1868f7504e0169cc1801e206eb8, and https://github.com/AviSynth/AviSynthPlus/commit/452cea0511397719e9d1861dc8cb47a73a591623.

The only one that was an actual issue was the use of $ENV{HOME} in the variable setting for the configurable user directory, as a better user-agnostic method was already in use for the directory you didn't mention and would have worked just fine: `$HOME/.avisynth` (barring some weird interaction with how the sandboxing works, but then it probably would not like `.local` either).  The other two commits are merely added creature comforts.

At the same time, I'd be remiss if I didn't point out that none of this actually *prevents* AviSynth+ from working, because the defaults are just that: defaults.  The user still has the power to add additional directories, or load individual plugins manually by using the exact same function(s) the core does: `AddAutoloadDir` and `LoadPlugin`.

AppImage and Flatpak are - at least as far as I was able to find - supposed to set `LD_LIBRARY_PATH` during launch, which is the proper way to override the location given to the dynamic linker that tries to load libavisynth.[so|dylib].  It's also far simpler to check for.
