### ISSUE TITLE
[Feature Request] ListAutoloadDirs

### ISSUE THREAD

**Issue by qyot27** [AviSynth/AviSynthPlus#413]
What it says on the tin.  In troubleshooting the commits associated with addressing #412, I realized that it doesn't look like we have any means to see which plugin directories *are* already loaded, especially when it can vary given the addition of searching `LD_LIBRARY_PATH`.  There didn't even seem to be a variable that could be printed through Subtitle() to show it.

**Comment by qyot27** [comment]
Unless using CR in Subtitle causes issues on Linux, etc., I don't have a preference.  Although at that point wouldn't that imply Subtitle should be extended to support either line ending style (or even `\n` style explicit escape character syntax, I can't remember whether it already does)?

**Comment by pinterf** [comment]
Subtitle supports multiline only when lsp=0 _and_ the new line charaters _must_ use "\n" ( in C: "\\n") explicitely.
Text recognizes LF control characters out of box, displaying nice multiline list of directories.

So I simply implemented the real LF-0x0a control character as a separator, and I won't implement Subtitle's special oddity.

When someone would really want to use Subtitle instead of Text, then the string must be character replaced.
