### ISSUE TITLE
ImageWriter: upside down image when colorspace is Y8.

### ISSUE THREAD

**Issue by Reel-Deal** [AviSynth/AviSynthPlus#58]
ImageWriter: upside down image when colorspace is Y8. FlipVertical() before ImageWriter fixes the problem.

Test script:

```
BlankClip(length=1, width=512, height=256, pixel_type="Y8", color_yuv=$808080)
Subtitle("Test", size=128, align=5)
ImageWriter(file="C:\", type="png")
```
- Using the following types writes an upside down image:  bmp, bw, dds, jpg, png. pbm, pgm, ppm, rgb, rgba, sgi, and tga.
- I tried with ebmp and tif/tiff, even though it writes the file I cannot open them, maybe they don't support Y8?
- file="pal" - ImageWriter: error 'illegal operation' in DevIL library - writting file "c:\000000.pal" - DevIL version 0.
- file="pcx" - it just returns a black frame.
- file="raw" - works correctly.
- I viewed images in GIMP and Photoshop.

**Comment by qyot27** [comment]
Well, you're crossing the RGB threshold, even if implicitly on write (because standalone image formats that support non-RGB are rarer, or when they do, the tools to read/write them may be scarce), and RGB formats requiring vertical flipping is a common thing.  You'll notice that 2.6 RC1 also exhibits this behavior.


EBMP is an AviSynth-specific extension; GIMP and Photoshop are what don't support it, rather than it having issues with Y8.  You have to use ImageSource() for EBMP files.

You could always just write the image(s) with ffmpeg:
```
ffmpeg -i test.avs output.png
```
Although the selection of output image formats is probably not as diverse.  But outputting to png and then using ImageMagick is an option for exotic formats (or use ImmaAvs).
