### ISSUE TITLE
Add exception clause back to avisynth.h

### ISSUE THREAD

**Issue by Reel-Deal** [AviSynth/AviSynthPlus#62]
Since AviSynth 2.6 was finally finalized, the exception clause can now be added back to avisynth.h.

On a side note, I know AviSynth+ was trying to relicense to MIT. Does this help the situation any?

**Comment by tp7** [comment]
The most liberal we wanted to go was LGPLv2 because the contributors would never allow MIT. 

Unfortunately no, this change doesn't help the re-licensing plan. The whole thing is blocked at IanB ignoring any questions about licensing and unless that changes we can't do anything.

**Comment by qyot27** [comment]
Preliminarily, the rc2integrate branch/pull request has the exception clause rollback cherry-picked from CVS, but it can always be omitted from being merged upstream if the consensus is that it's not possible to re-add it.  Hell, I remember people questioning if it was even legal for IanB to *remove* the exception in the first place, so the whole thing has the potential to be one huge clusterfuck.  If you want to be absolutely safe, use the C header - it was never screwed around with, and upgraded from 2.5 to 2.6 with the exception intact the entire time.

The *only* change from RC2/RC3 to Final was the exception clause returning to the C++ header.  It'd be nice if we can go ahead and do 0.2 stable since 2.6 went Final, with or without the exception mess.

**Comment by innocenat** [comment]
Aside from bumping header version from 5 to 6, I think we can go around the x64 change by just use the new header and changing those back (say, for compatibility). That should be okay under GPL, IMO.

**Comment by qyot27** [comment]
The header version is *already* bumped to 6.  It happened during the RC1 integration.

IANAL, but from what I remember when I was integrating the changes from RC1, there didn't seem to be a lot of avsplus-specific changes to avisynth.h - mostly pruning out the stuff that had been split out into the avs/ headers (I simply ignored the int->size_t stuff in RC1 because we already had 64-bit support).  I have a feeling the end result of using the fixed header from Final and reapplying our changes on top of it would end up looking exactly the same as simply restoring the exception clause, so it becomes a question of commit procedure (update to the Final header and ditch our current versions, but then reapply those changes onto the Final header, effectively restoring what we already have but with the exception header).

**Comment by pylorak** [comment]
Exemption restored with merge 58107d6e5c01ec0d4ef732de09a8028e1dd31e99.
